name: Deploy GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update npm
        run: npm install npm@v8 -g

      - name: Install packages
        run: npm install

      - name: Build static site
        run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          # Path of the directory containing the static assets.
          path: blog/.vuepress/dist
  deploy:
    environment:
      name: github-pages
      url: 'https://www.dan-gee.co.uk'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.1
