name: Deploy GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update npm
        run: npm install npm@v7 -g

      - name: Install packages
        run: npm install

      - name: Build static site
        run: npm run build